docker_file/django_project/bookmark/urls.py
from django.urls import path
from bookmark.views import StockLV, StockDV, stockDB

app_name = 'bookmark'

urlpatterns = [
    path('', stockDB, name='stock_list'),
    path('detail', StockDV.stockDB_detail, name='stock_detail'),
]

docker_file/django_project/mysite2/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite2.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('bookmark/', include('bookmark.urls', namespace='bookmark')),
]

docker_file/django_project/bookmark/models.py
from django.db import models


class Post(models.Model):
    objects = models.Manager()

    symbol = models.CharField('SYMBOL', unique=True, max_length=50)
    name = models.CharField('NAME', max_length=100)
    price = models.CharField('PRICE', max_length=50)
    open = models.CharField('OPEN', max_length=50)
    day_min = models.CharField('DAY_MIN', max_length=50)
    day_max = models.CharField('DAY_MAX', max_length=50)
    volume = models.CharField('VOLUME', max_length=50)
    modify_date = models.CharField('Modify Date', max_length=50)

    def __str__(self):
        return self.symbol

    class Meta:
        db_table = "blog_post"

docker_file/django_project/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from bookmark.models import Post


class StockLV(ListView):
    model = Post
    template_name = "stock/stock_search.html"


def stockDB(request):
    stock = Post.objects.all().order_by('-id')
    context = {'stocks': stock}

    return render(request, 'stock/stock_search.html', context)


class StockDV(DetailView):
    model = Post
    template_name = "stock/stock_detail.html"

    @method_decorator(csrf_exempt)
    def stockDB_detail(request):
        name = request.POST.get('name')
        print(name)
        stock = Post.objects.get(name=name)
        context = {'stocks': stock}

        return render(request, 'stock/stock_detail.html', context)

docker_file/django_project/mysite2/views.py
from django.views.generic import TemplateView, FormView
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
import os


class HomeView(TemplateView):
    template_name = 'home.html'

docker_file/django_project/bookmark/templates/stock/stock_detail.html
<title>Stock Searched List</title>


<div id="masthead">
    <tr>
        <td><h3>종목 상세</h3></td>
            <li>Symbol : {{ stocks.symbol }}</li>
            <li>Symbol : {{ stocks.name }}</li>
            <li>Price : {{ stocks.price }}</li>
            <li>Open : {{ stocks.open }}</li>
            <li>Day_Min : {{ stocks.day_min }}</li>
            <li>Day_Max : {{ stocks.day_max }}</li>
            <li>Volume : {{ stocks.volume }}</li>
    </tr>
</div>

docker_file/django_project/bookmark/templates/stock/stock_search.html
<title>Stock Searched List</title>


<div id="masthead">
    <tr>
        <td><h3>검색 한 종목(hello)</h3></td>
        {% for stock in stocks %}
            <form action="detail" method="post">
                <input type="submit" name="name" value="{{ stock.name }}"
                        onclick="location.href='{% url 'bookmark:stock_detail' %}'">
            </form>
            <br><br>
        {% endfor %}
    </tr>
</div>